version: "3.8"

services:
  react-app:
    image: node:18-alpine # Use Node.js 18 for compatibility
    container_name: react-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"
